language: node_js
script: make test-sauce
node_js:
- '0.12'
env:
  global:
  - secure: LoNu6uwsubuGa63PgPfXDlNSOdJ7PdPlk3hgadnAdYpskrDtg4op7uNREpf6ZYbJEKHmCMfgN7bqPEakw3Lnfw0f+HAteJmRdc2TJ6Ntq+ZF8H7hDdD7vWx6PUOK2VuDyNNRkWj1Imxm4ZF+TCgItdNFVjn8RifwVqsXIgCZPLs=
  - secure: CkzgZbbMfR2LgKvigLs8kSgXQYZw8w1f9NrFoppTTEbJD13EiVj7FWF9EH4PFvINEeuFZb3f0lvwCq2PGpMtl5ckyfXXoDdNNUTkJbL5D6wm9pkKu09G74LZ20vT/U5HIs+o7/E2ARRrhH/nTY2rJysuDlcjkZ3lkDm5CIG888k=
  - secure: ixFsGpkqQty4f8kTOZFq+BF3nmkMCHqQKCaXdgtOEADJXpRoqWtGnAgM1EXF0fDsmf825E+gxwJbBk7lBgCykOnToVmXsoNoPyLA8c/rjWVwFBwFcrRidaR7qbAbWQr1qGxEWwveP5ijj8neEXs9cslwv1y31WCBjXaz/ZHvEnI=
  - secure: F5GN7Ph+7qcM/QPekFuaOZzzRA4+NpfdmVxdQPJZuEy4GTAdM3USzPBuYebxji6DQjplGXM0szUIZPuwWJowHVzUvbY4OuwYHGbIJm0Sc9ZR78DFCPIMIZ577rliqybvpKWjl9eXGacre8sa5UzQdL7z0CI8xDzdrmHnr23hkeY=
  matrix:
  - BROWSER=chrome
  - BROWSER=firefox
  - BROWSER=safari
  - BROWSER=ie:11
  - BROWSER=ie:10
  - BROWSER=ie:9
  - BROWSER=ie:8
